on:
  schedule:
    - cron:  '0 14 * * sun-sat'
    # scheduled at 14:00 UTC (22:00 local) every days
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v2.2
      with:
        upstream_repository: pojiezhiyuanjun/freev2
        upstream_branch: master
        target_branch: master
        git_pull_args: --allow-unrelated-histories

    - name: Timestamp
      run: date
